spring.application.name=ai-service
server.port=8082
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5434/taskflow_ai
spring.datasource.username=postgres
spring.datasource.password=${AI_DB_PASSWORD}

spring.ai.vectorstore.pgvector.initialize-schema=true

# MCP Client
spring.ai.mcp.client.name=taskflow-ai-service
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC

# task-mcp-server connection
spring.ai.mcp.client.streamable-http.connections.task-server.url=http://localhost:8084
spring.ai.mcp.client.streamable-http.connections.task-server.endpoint=/mcp
